Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:37:12) [MSC v.1600 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
привет
п
---
р
---
и
---
в
---
е
---
т
---
>>> ================================ RESTART ================================
>>> 
привет
п
ппп
р
ррр
и
иии
в
ввв
е
еее
т
ттт
>>> ================================ RESTART ================================
>>> 
привет
ппп
ррр
иии
ввв
еее
ттт
>>> ================================ RESTART ================================
>>> 
привет
1
1
1
1
1
1
>>> ================================ RESTART ================================
>>> 
привет
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 8, in <module>
    print (i)
NameError: name 'i' is not defined
>>> ================================ RESTART ================================
>>> 
привет
п
р
и
в
е
т
>>> ================================ RESTART ================================
>>> 
привет
п
ппп
р
ррр
и
иии
в
ввв
е
еее
т
ттт
>>> ================================ RESTART ================================
>>> 
привет
п
р
и
в
е
т
ттт
>>> ================================ RESTART ================================
>>> 
привет
п
р
и
в
е
т
6
>>> ================================ RESTART ================================
>>> 
привет
п 0
р 1
и 2
в 3
е 4
т 5
6
>>> ================================ RESTART ================================
>>> 
привет
п
--------------------
п
>>> ================================ RESTART ================================
>>> 
привет
р
--------------------
р
>>> ================================ RESTART ================================
>>> 
привет
р
--------------------
р
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 19, in <module>
    print (a)
NameError: name 'a' is not defined
>>> ================================ RESTART ================================
>>> 
привет
р
--------------------
р
0
6
>>> ================================ RESTART ================================
>>> 
привет
р
--------------------
р
п
6
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 21, in <module>
    print(word(len(word)))
TypeError: 'str' object is not callable
>>> ================================ RESTART ================================
>>> 
привет
р
--------------------
р
6
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 21, in <module>
    print(word(len(word)-1))
TypeError: 'str' object is not callable
>>> ================================ RESTART ================================
>>> 
привет
р
--------------------
р
6
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 21, in <module>
    print(word(len(word)-1))
TypeError: 'str' object is not callable
>>> ================================ RESTART ================================
>>> 
привет
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 15, in <module>
    print(a)
NameError: name 'a' is not defined
>>> ================================ RESTART ================================
>>> 
привет
0
--------------------
6
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 21, in <module>
    print(word(len(word)-1))
TypeError: 'str' object is not callable
>>> ================================ RESTART ================================
>>> 
привет
п 0
р 1
и 2
в 3
е 4
т 5
6
--------------------
6
т
и
>>> ================================ RESTART ================================
>>> 
привет
п 0
р 1
и 2
в 3
е 4
т 5
6
----------
6
т
и
>>> ================================ RESTART ================================
>>> 
привет
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 32, in <module>
    print(letter)
NameError: name 'letter' is not defined
>>> ================================ RESTART ================================
>>> 
привет
р
в
т
>>> ================================ RESTART ================================
>>> 
привет
ив
р
в
т
>>> ================================ RESTART ================================
>>> 
привет
ив
р
в
т
>>> ================================ RESTART ================================
>>> 
привет
при!вет!
р
в
т
>>> ================================ RESTART ================================
>>> 
привет
0 <class 'int'>
1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4 <class 'int'>
>>> ================================ RESTART ================================
>>> 
привет
3 <class 'int'>
5 <class 'int'>
7 <class 'int'>
9 <class 'int'>
11 <class 'int'>
13 <class 'int'>
15 <class 'int'>
17 <class 'int'>
19 <class 'int'>
>>> ================================ RESTART ================================
>>> 
привет
3
5
7
9
11
13
15
17
19
>>> ================================ RESTART ================================
>>> 
привет
121
169
225
289
361
>>> ================================ RESTART ================================
>>> 
привет
0
0
0
0
121
1
1
169
2
2
225
3
3
289
4
4
361
5
5
>>> ================================ RESTART ================================
>>> 
привет
0
0
0
0
121
11
11
169
24
24
225
39
39
289
56
56
361
75
75
>>> ================================ RESTART ================================
>>> 
привет
3
8
15
24
35
48
63
80
99
99
>>> ================================ RESTART ================================
>>> 
введите: 6
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 50, in <module>
    a+=i
NameError: name 'i' is not defined
>>> ================================ RESTART ================================
>>> 
введите: 6
0
1
3
6
10
15
15
>>> ================================ RESTART ================================
>>> 
введите: 6
0
1
3
6
10
15
21
21
>>> ================================ RESTART ================================
>>> 
введите: 
>>> ================================ RESTART ================================
>>> 
10
9
8
7
6
5
>>> ================================ RESTART ================================
>>> 
2
3
4
5
6
7
8
9
10
11
>>> ================================ RESTART ================================
>>> 
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
10 100
11
>>> ================================ RESTART ================================
>>> 
end
>>> ================================ RESTART ================================
>>> 
0
1
2
3
4
5
end
>>> ================================ RESTART ================================
>>> 
0
1
2
3
4
5
6
7
end
>>> ================================ RESTART ================================
>>> 

0  0

1  1

2  4

3  9

4  16

5  25

6  36

7  49

8  
9  81
end
>>> ================================ RESTART ================================
>>> 
введите слово: мев
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 2, in <module>
    word=int(input('введите слово: '))
ValueError: invalid literal for int() with base 10: 'мев'
>>> ================================ RESTART ================================
>>> 
введите слово: мев
3
введите слово: нора
4
введите слово: куруру
6
введите слово: 
>>> ================================ RESTART ================================
>>> 
vvedite chislo: 87
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 10, in <module>
    for i in range ():
TypeError: range expected 1 arguments, got 0
>>> ================================ RESTART ================================
>>> 
vvedite chislo: 87
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 10, in <module>
    for i in range ():
TypeError: range expected 1 arguments, got 0
>>> ================================ RESTART ================================
>>> 
vvedite chislo: 87
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 10, in <module>
    for num in range ():
TypeError: range expected 1 arguments, got 0
>>> ================================ RESTART ================================
>>> 
kolichestvo2
Traceback (most recent call last):
  File "C:/Users/student/Desktop/ttt.py", line 10, in <module>
    for i in range (num):
NameError: name 'num' is not defined
>>> ================================ RESTART ================================
>>> 
kolichestvo2
vvedite chislo: 5
bolshe
vvedite chislo: -8
menshe
>>> 0
0
>>> 
